name: MagicWands
version: ${project.version}
author: nahkd123
description: Add programmable magic wands to your server
website: https://github.com/nahkd123/MagicWands

main: me.nahkd.spigot.sfaddons.MagicWands.MagicWands
depend: [Slimefun]

api-version: 1.15