name: SlimefunAddon
version: ${project.version}
author: CHANGEME
description: A generic Slimefun4-Addon
website: https://github.com/TheBusyBiscuit/Slimefun4-Addon

main: me.CHANGEME.slimefunaddon.ExampleAddon
depend: [Slimefun]

api-version: 1.14